### ISSUE TITLE
Allow creation of GPU memory views in config file

### ISSUE THREAD

**Issue by dstndstn** [kotekan/kotekan#1122]
If we can create GPU memory views in the config file, then we can get rid of the gnarly chordMVPSetup.cpp

Eg, the upchan/frb-bf glue buffer could look like this in YAML:
```
gpu_mem_views:
    # Glue between upchannelizer & FRB-1 beamformer to allow for variable overlaps
    - real_name: bf_input
      real_size: num_dishes * (voltage_freq * frb_upchan) * (frb_samples + frb_bf_padding) * 2
      view_name: upchan_out
      view_offset: num_dishes * (voltage_freq * frb_upchan) * frb_bf_padding * 2
      view_size: num_dishes * (voltage_freq * frb_upchan) * frb_samples * 2
```
