### ISSUE TITLE
RNG Seed in testDataGen is hard coded to 42

### ISSUE THREAD

**Issue by james-s-willis** [kotekan/kotekan#482]
`testDataGen` and `testDataGenFloat` stages seed their RNG with `42`, instead of using the `value` field in the config file:

```
gen_data:
  type: random
  value: 153                                                                                                                                                                                                       
  test_data_gen_0:
    kotekan_stage: testDataGen
    network_out_buf: network_buffer_0
```
