### ISSUE TITLE
Improve memory and copy abstraction in GPU stages

### ISSUE THREAD

**Issue by andrerenard** [kotekan/kotekan#491]
Currently there are a lot of command objects in the GPU stage which either copy memory into the GPU or out of the GPU into a standard buffer.  At the moment one of these is created for every type of input/output data.  However there is no reason this couldn't be made a generic command object in the vast majority of cases. 

The main requirement for this to work is the config parsing engine for the GPU commands needs to be updated to allow `local scope` modifications, and the GPU memory references need to be moved into the configuration (currently they are hardcoded). 

For example the commands might look like this:
```
commands:
- name: HostToDeviceCopy
  in_buf: network_capture_buf
  gpu_mem: input_data   
- name: CorrKernel
  gpu_input_mem: input_data
  gpu_output_mem: n2_output
- name: DeviceToHostCopy
  out_buf: host_n2_output
  gpu_mem: n2_output
```

This will result in longer configuration files, but it will also remove about 6-8 command objects which are currently error prone, and stop us from continuing to write new input/output command objects for most cases.
