### ISSUE TITLE
Add no tracking option to the tracking beamformer

### ISSUE THREAD

**Issue by andrerenard** [kotekan/kotekan#680]
In hotfix `2019.12b` we added a condition to not apply a tracking phase to the Pulsar/Tracking beamfomer.  That condition is when `scaling == 1`, this was the safest way to do it as a hotfix, but it is a bit of a hack.  Ideally we'd have an option in the config to enable/disable the tracking on each beam with any scaling.  i.e.

```
  pulsar_pointing:
    0:
      kotekan_update_endpoint: json
      ra: 42
      dec: 54
      scaling: 42
      tracking_beam: <true|false>
```

This ticket is related to #674 since this is a feature that we want to support in the extra beams.  This is being split out into its own ticket since it will likely be implemented before the extra beams are added.
