### ISSUE TITLE
Breakup tracking beam gains endpoint

### ISSUE THREAD

**Issue by andrerenard** [kotekan/kotekan#799]
Currently the tracking beams endpoint looks like this: 
```
  pulsar_gain:
    kotekan_update_endpoint: json
    pulsar_gain_dir:
      - /mnt/frb-archiver/daily_gain_solutions/Latest_PSR
      - /mnt/frb-archiver/daily_gain_solutions/Latest_PSR
      - /mnt/frb-archiver/daily_gain_solutions/Latest_PSR
      - /mnt/frb-archiver/daily_gain_solutions/Latest_PSR
      - /mnt/frb-archiver/daily_gain_solutions/Latest_PSR
      - /mnt/frb-archiver/daily_gain_solutions/Latest_PSR
      - /mnt/frb-archiver/daily_gain_solutions/Latest_PSR
      - /mnt/frb-archiver/daily_gain_solutions/Latest_PSR
      - /mnt/frb-archiver/daily_gain_solutions/Latest_PSR
      - /mnt/frb-archiver/daily_gain_solutions/Latest_PSR
```
 Which makes it hard for independent backends to share beams.   At a minimum this should be broken up into individual endpoints for controlling each beam's gains, like with the current beam pointing.
