### ISSUE TITLE
Metadata pointer is NULL in EigenVisIter for multi frequency streems

### ISSUE THREAD

**Issue by andrerenard** [kotekan/kotekan#992]
Adam reports that EigenVisIter gets a NULL metadata pointer at random times.   The metadata should be set by visAccumulate.   When using superdebug, it appears to change the timing of the system and the error no longer appears.  This points to a race condition between visAccumulate and EigenVisIter, which is quite concerning, since that should be handled safely by the buffer object. 

This condition was hit while running in docker, with gcc 7.5.0 and the following CMAKE options:
```
        -DCMAKE_BUILD_TYPE=Debug \
        -DCMAKE_CXX_FLAGS_DEBUG="-g -O0"\
        -DCMAKE_C_FLAGS_DEBUG="-g -O0" \
        -DSUPERDEBUG=ON \
        -DBLAZE_PATH=/code/build/blaze \
        -DBLAS_LIBRARIES=/usr/lib/x86_64-linux-gnu/libopenblas.so.0 \
        -DLAPACK_LIBRARIES=/usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1 \
        -DCMAKE_BUILD_TYPE=Debug \
        -DUSE_HDF5=ON \
        -DUSE_LAPACK=ON \
        -DHIGHFIVE_PATH=/code/build/HighFive \
```

The configuration used is:
```
# Configuration for GPU to calibration pipeline at Allenby.


#--------------------------
# Global options
#--------------------------
type: config
log_level: info
num_elements: 128
cpu_affinity: []
buffer_depth: 10 
num_local_freq: 16  #16
num_freq_in_frame: 16 # 16
num_data_sets: 1
num_ev: 4
block_size: 1 
samples_per_data_set: 49152

dataset_manager:
  use_dataset_broker: false


#--------------------------
#  Pools
#--------------------------
main_pool:
  kotekan_metadata_pool: chimeMetadata
  num_metadata_objects: 30 * buffer_depth
vis_pool:
  kotekan_metadata_pool: VisMetadata
  num_metadata_objects: 30 * buffer_depth


#--------------------------
# Buffers
#--------------------------
fakegpu_buf0:
  frame_size: "sizeof_int * num_freq_in_frame * ((num_elements * num_elements) + (num_elements * block_size))"
  kotekan_buffer: standard
  metadata_pool: main_pool
  num_frames: buffer_depth
  sizeof_int: 4
dumpvis_buf0:
  kotekan_buffer: vis
  metadata_pool: vis_pool
  num_frames: buffer_depth
vis_int_buffers:
  metadata_pool: vis_pool
  num_frames: buffer_depth
  visbuf_5s_0:
    kotekan_buffer: vis
  visbuf_10s_0:
    kotekan_buffer: vis
  visbuf_eig_10s_0:
    kotekan_buffer: vis
  visbuf_10s_cal:
    kotekan_buffer: vis


#--------------------------
# Stages
#--------------------------
fakegpu0:
        #freq: 777 
  freq: 0
  kotekan_stage: FakeGpu
  #  num_frames: 257
  out_buf: fakegpu_buf0
  pattern: gaussian
  pre_accumulate: true 
  wait: false 

vis_accumulate:
  integration_time: 10.0 
  kotekan_stage: visAccumulate
  in_buf: fakegpu_buf0 
  out_buf: visbuf_10s_0

eigcalc:
  kotekan_stage: EigenVisIter
  cpu_affinity: [1]
  log_level: warn
  in_buf: visbuf_10s_0
  out_buf: visbuf_eig_10s_0
  tol_eval: 0.00001
  tol_evec: 0.0001
  max_iterations: 19
  num_ev_conv: 2
  krylov: 2
  subspace: 1

# Generate the calibration stream
# (Normally flagging is applied first, but there is no flagging data for this test).
cal_subset:
  kotekan_stage: prodSubset
  in_buf: visbuf_eig_10s_0
  out_buf: visbuf_10s_cal
  prod_subset_type: autos

count_check:
  cal:
    kotekan_stage: countCheck
    in_buf: visbuf_10s_cal

vis_shm_buffer:
  cal:
    kotekan_stage: VisSharedMemWriter
    in_buf: visbuf_10s_cal
    name: calshm
    num_samples: 256

```
